var players=[{
    "id": 1,
    "playername": "Mashrafe Mortaza",
    "born": "Oct 05, 1983",
    "Role": "Bowler",
    "batting_style": "Right Handed Bat",
    "bowling_style":"Right-arm fast-medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170920/mashrafe-mortaza.jpg",
    "income": 4637.96,
    "team": "Dhaka Platoon",
    "age": "37 years"
  }, {
    "id": 2,
    "playername": "Shakib Al Hasan",
    "born": "Mar 24, 1987",
    "Role": "Batting Allrounder",
    "batting_style": "Left Handed Bat",
    "bowling_style": "Left-arm orthodox",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170912/shakib-al-hasan.jpg",
    "income": 4637.96,
    "team": "Dhaka Platoon",
    "age": "33 years"
  }, {
    "id": 3,
    "playername": "Tamim Iqbal",
    "born": "Mar 20, 1989",
    "Role": "Batsman",
    "batting_style": "Left Handed Bat",
    "bowling_style": "NaN",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170899/tamim-iqbal.jpg",
    "income": 4637.96,
    "team": "Dhaka Platoon",
    "age": "31 years"
  }, {
    "id": 4,
    "playername": "Mushfiqur Rahim",
    "born": "Jun 09, 1987",
    "Role": "WK-Batsman",
    "batting_style": "Right Handed Bat",
    "bowling_style": "NaN",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170916/mushfiqur-rahim.jpg",
    "income": 4637.96,
    "team": "Khulna Tigers",
    "age": "33 years"
  }, {
    "id": 5,
    "playername": "Mahmudullah",
    "born": "Feb 04, 1986",
    "Role": "Batting Allrounder",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm offbreak",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170905/mahmudullah.jpg",
    "income": 4637.96,
    "team": "Chattogram Challengers",
    "age": "35 years"
  }, {
    "id": 6,
    "playername": "Mustafizur Rahman",
    "born": "Sep 06, 1995",
    "Role": "Bowler",
    "batting_style": "Left Handed Bat",
    "bowling_style": "Left-arm fast-medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170925/mustafizur-rahman.jpg",
    "income": 3478.47,
    "team": "Rangpur Rangers",
    "age": "25 years"
  }, {
    "id": 7,
    "playername": "Rubel Hossain",
    "born": "Jan 01, 1990",
    "Role": "Bowler",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm fast-medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170922/rubel-hossain.jpg",
    "income": 3478.47,
    "team": "Chattogram Challengers",
    "age": "31 years"
  }, {
    "id": 8,
    "playername": "Mehidy Hasan",
    "born": "Oct 25, 1997",
    "Role": "Bowling Allrounder",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm offbreak",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c148289/mehidy-hasan.jpg",
    "income": 2318.98,
    "team": "Khulna Tigers",
    "age": "23 years"
  }, {
    "id": 9,
    "playername": "Liton Das",
    "born": "Oct 13, 199",
    "Role": "WK-Batsman",
    "batting_style": "Right Handed Bat",
    "bowling_style": "NaN",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170914/liton-das.jpg",
    "income": 2318.98,
    "team": "Rajshahi Royals",
    "age": "26 years"
  }, {
    "id": 10,
    "playername": "Abu Jayed",
    "born": "Aug 02, 1993",
    "Role": "Bowler",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm fast-medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170927/abu-jayed.jpg",
    "income": 1159.49,
    "team": "Rajshahi Royals",
    "age": "27 years"
  }, {
    "id": 11,
    "playername": "Mohammad Saifuddin",
    "born": "Nov 01, 1996",
    "Role": "Batting Allrounder",
    "batting_style": "Left Handed Bat",
    "bowling_style": "Right-arm fast-mediu",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170907/mohammad-saifuddin.jpg",
    "income": 1159.49,
    "team": "Rajshahi Royals",
    "age": "24 years"
  }, {
    "id": 12,
    "playername": "Mosaddek Hossain",
    "born": "Dec 10, 1995",
    "Role": "Batting Allrounder",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm offbreak",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170909/mosaddek-hossain.jpg",
    "income": 2318.98,
    "team": "Sylhet Thunder",
    "age": "25 years"
  }, {
    "id": 13,
    "playername": "Soumya Sarkar",
    "born": "Feb 25, 1993",
    "Role": "Batsman",
    "batting_style": "Left Handed Bat",
    "bowling_style": "Right-arm medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170900/soumya-sarkar.jpg",
    "income": 3478.47,
    "team": "Cumilla Warriors",
    "age": "28 years"
  }, {
    "id": 14,
    "playername": "Imrul Kayes",
    "born": "Feb 02, 1987",
    "Role": "Batsman",
    "batting_style": "Left Handed Bat",
    "bowling_style": "NaN",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c148273/imrul-kayes.jpg",
    "income": 3478.47,
    "team": "Chattogram Challengers",
    "age": "34 years"
  }, {
    "id": 15,
    "playername": "Mohammad Mithun",
    "born": "Mar 02, 1991",
    "Role": "WK-Batsman",
    "batting_style": "Right Handed Bat",
    "bowling_style": "NaN",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170918/mohammad-mithun.jpg",
    "income": 1159.49,
    "team": "Sylhet Thunder",
    "age": "29 years"
  }, {
    "id": 16,
    "playername": "Sabbir Rahman",
    "born": "Nov 22, 1991",
    "Role": "Batsman",
    "batting_style": "Right Handed Bat",
    "bowling_style": "Right-arm legbreak",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c170903/sabbir-rahman.jpg",
    "income": 3478.47,
    "team": "Cumilla Warriors",
    "age": "29 years"
  }, {
    "id": 17,
    "playername": "Taskin Ahmed",
    "born": "Mar 04, 1995",
    "Role": "Bowler",
    "batting_style": "Left Handed Bat",
    "bowling_style": "Right-arm fast-medium",
    "img": "https://www.cricbuzz.com/a/img/v1/152x152/i1/c156212/taskin-ahmed.jpg",
    "income": 2318.98,
    "team": "Rangpur Rangers",
    "age": "25 years"
  }];
  export default players;